#get the scheduler
FROM ghcr.io/equinor/task-scheduler:latest as scheduler

#run the scheduler in a shell
FROM alpine:3.20.3
COPY --from=scheduler /scheduler /scheduler
USER 1000
CMD ["/scheduler", "--command=echo \"test\"", "--schedule=0/5 * * * * *", "--verbose"]
